# Generated by Django 4.2.7 on 2023-11-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbillingaddress',
            old_name='address',
            new_name='house_number',
        ),
        migrations.AddField(
            model_name='userbillingaddress',
            name='country',
            field=models.CharField(default='dsa', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbillingaddress',
            name='street',
            field=models.CharField(default='dsa', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbillingaddress',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
