# Generated by Django 4.2.7 on 2023-11-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='API_URL',
            field=models.CharField(default='localhost', max_length=255),
            preserve_default=False,
        ),
    ]
