# Generated by Django 4.2.7 on 2023-11-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_api_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='locker_number',
            field=models.IntegerField(),
        ),
    ]
