# Generated by Django 4.2.7 on 2023-11-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_locker_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
