# Generated by Django 4.2.7 on 2023-11-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_rental_total_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
