# Generated by Django 4.2.7 on 2023-11-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_remove_rental_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
