# Generated by Django 4.2.7 on 2023-11-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_rental_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='is_rented',
            new_name='is_active',
        ),
    ]
