# Generated by Django 4.2.7 on 2023-11-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_rename_is_rented_rental_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
